version: '3.3'

services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    restart: always

  celery:
    build:
      context: ../
      dockerfile: ASODU/Dockerfile
    command: celery -A ASODU worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - ./logs/celery:/app/logs

volumes:
  db_data:
