# Generated by Django 4.2 on 2023-04-23 14:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Оборудование в щите', help_text='Добавьте описание оборудования.', max_length=500, verbose_name='Наименование, техническая характеристика')),
                ('code', models.CharField(help_text='Введите артикул/код оборудования', max_length=128, unique=True, verbose_name='Артикул/код оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentPanelAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Должно быть больше 0')], verbose_name='Количество')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panels.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=64, verbose_name='Завод изготовитель')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название проекта.', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', inverse_match=True, message='В названии необходимо использовать буквы.', regex='^[0-9\\W]+$')], verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Добавьте краткое описание проекта.', max_length=500, null=True, verbose_name='Описание')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ЩА-00', help_text='Введите название щита', max_length=64, verbose_name='Название щита')),
                ('function_type', models.CharField(choices=[('power', 'Силовой с локальной автоматикой'), ('automation', 'Локальная автоматика'), ('dispatch', 'Диспетчеризация'), ('room', 'Комнатная автоматика'), ('general', 'Общее назначение')], default='general', max_length=64)),
                ('description', models.TextField(default='Щит автоматизации общего назначения', help_text='Добавьте описание щита.', max_length=500, verbose_name='Наименование, техническая характеристика')),
                ('equipment', models.ManyToManyField(through='panels.EquipmentPanelAmount', to='panels.equipment', verbose_name='Оборудование в щите')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panels.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Щит',
                'verbose_name_plural': 'Щиты',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='equipmentpanelamount',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panels.panel'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panels.vendor', verbose_name='Производитель'),
        ),
        migrations.AddConstraint(
            model_name='panel',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_panel_in_project', violation_error_message='Имя щита должно быть уникальным в проекте'),
        ),
        migrations.AddConstraint(
            model_name='equipmentpanelamount',
            constraint=models.UniqueConstraint(fields=('equipment', 'panel'), name='unique_equipment_in_panel'),
        ),
    ]
