# Generated by Django 4.2 on 2023-06-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_alter_vendor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('code',), 'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
    ]
