# Generated by Django 4.2 on 2023-06-11 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panels', '0004_equipmentgroup_equipment_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentgroup',
            options={'ordering': ('title',), 'verbose_name': 'Группа оборудования', 'verbose_name_plural': 'Группы оборудования'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('created',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panels.equipmentgroup', verbose_name='Группа оборудования'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
