# Generated by Django 4.2 on 2023-06-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0005_alter_equipmentgroup_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
