# Generated by Django 4.2 on 2023-06-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0007_alter_project_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentpanelamount',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
    ]
