# Generated by Django 4.2 on 2024-01-31 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0010_attachment_alter_equipmentpanelamount_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='attachements',
            new_name='attachments',
        ),
    ]
