# Generated by Django 4.2 on 2024-01-31 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0011_rename_attachements_panel_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='attachments',
        ),
        migrations.AddField(
            model_name='panel',
            name='attachments',
            field=models.ForeignKey(blank=True, help_text='Загрузите схемы.', null=True, on_delete=django.db.models.deletion.CASCADE, to='panels.attachment', verbose_name='Файлы'),
        ),
    ]
