# Generated by Django 4.2 on 2024-01-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0012_remove_panel_attachments_panel_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='attachments',
        ),
        migrations.AddField(
            model_name='panel',
            name='attachments',
            field=models.ManyToManyField(blank=True, help_text='Загрузите схемы.', to='panels.attachment', verbose_name='Файлы'),
        ),
    ]
