# Generated by Django 4.2 on 2024-01-31 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0013_remove_panel_attachments_panel_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='attachments',
        ),
        migrations.AddField(
            model_name='attachment',
            name='panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='panels.panel'),
        ),
        migrations.AddField(
            model_name='panel',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='Загрузите схемы.', related_name='panels', to='panels.attachment', verbose_name='Файлы'),
        ),
    ]
