# Generated by Django 4.2 on 2024-01-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0015_alter_attachment_options_alter_attachment_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.TextField(help_text='Добавьте краткое описание файла', max_length=256, null=True, verbose_name='Наименование чертежа'),
        ),
    ]
