# Generated by Django 4.2 on 2024-01-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0016_attachment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.CharField(default='Чертеж', help_text='Добавьте краткое описание файла', max_length=256, null=True, verbose_name='Наименование чертежа'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='drawing',
            field=models.FileField(blank=True, help_text='Загрузите файл', null=True, upload_to='panels/', verbose_name='Файл'),
        ),
    ]
