# Generated by Django 4.2 on 2024-01-31 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0017_alter_attachment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='drawing',
            field=models.FileField(help_text='Загрузите файл', upload_to='panels/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='panels.panel'),
        ),
    ]
