# Generated by Django 4.2 on 2024-11-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0019_alter_attachment_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Открыть доступ для просмотра всем', verbose_name='Флаг общего доступа'),
        ),
    ]
