# Generated by Django 4.2 on 2024-11-18 07:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panels', '0020_project_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletableObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален из просмотра пользователями')),
                ('date_deleted', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='co_projects', to=settings.AUTH_USER_MODEL, verbose_name='Соавторы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Добавьте краткое описание', max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Введите название проекта', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', inverse_match=True, message='В названии необходимо использовать буквы.', regex='^[0-9\\W]+$')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=254, verbose_name='Завод изготовитель'),
        ),
    ]
