# Generated by Django 4.2 on 2024-11-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0021_deletableobject_project_co_authors_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipmentpanelamount',
            name='unique_equipment_in_panel',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=254, unique=True, verbose_name='Завод изготовитель'),
        ),
        migrations.AddConstraint(
            model_name='equipmentpanelamount',
            constraint=models.UniqueConstraint(fields=('equipment', 'panel'), name='unique_equipment_in_panel', violation_error_message='Такое оборудование уже есть в этом щите'),
        ),
    ]
