# Generated by Django 4.2 on 2024-11-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0022_remove_equipmentpanelamount_unique_equipment_in_panel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(help_text='Введите артикул/код оборудования', max_length=128, verbose_name='Артикул/код оборудования'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('code', 'vendor'), name='unique_code_in_vendor', violation_error_message='Не может быть два типа оборудования с одинаковым кодом у одного вендора'),
        ),
    ]
