# Generated by Django 4.2 on 2024-12-03 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0023_alter_equipment_code_equipment_unique_code_in_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentgroup',
            options={'ordering': ('group_priority', 'title'), 'verbose_name': 'Группа оборудования', 'verbose_name_plural': 'Группы оборудования'},
        ),
        migrations.AddField(
            model_name='equipmentgroup',
            name='group_priority',
            field=models.IntegerField(default=100, help_text='0-255, чем меньше значение тем выше в списке оборудования будет отображаться эта группа', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Приоритет сортировки'),
        ),
    ]
